"""Adding messages

Revision ID: 0119a0ace3a2
Revises: c79b6d6c7f52
Create Date: 2023-06-28 16:45:32.922296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0119a0ace3a2'
down_revision = 'c79b6d6c7f52'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
