"""Adding messages

Revision ID: 848fa740651a
Revises: 0119a0ace3a2
Create Date: 2023-06-28 16:48:42.892348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '848fa740651a'
down_revision = '0119a0ace3a2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
