"""Adding messages2

Revision ID: e3cc310f3dc5
Revises: 848fa740651a
Create Date: 2023-06-28 16:49:05.061174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3cc310f3dc5'
down_revision = '848fa740651a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
